"""add product views

Revision ID: 966035846887
Revises: 7e1420287e35
Create Date: 2026-09-12 12:55:29.933089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966035846887'
down_revision: Union[str, Sequence[str], None] = '7e1420287e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productsTable', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'productsTable', 'brandTable', ['brand_id'], ['id'])
    op.drop_column('productsTable', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productsTable', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'productsTable', type_='foreignkey')
    op.drop_column('productsTable', 'brand_id')
    # ### end Alembic commands ###
